export  const projectData=[{date:'11-12 OCT 2000', topic:'Conflict transformation skill training workshop ', Sponsor:"ALFACARE"},
    {date:'30APR – 5MAY 2001', topic:'5 days Zonal workshop on conflict management training (North west) ', Sponsor:'USAID OTI'},
    {date:'17 JULY 2001', topic:'Kaduna peace conflict resolution training', Sponsor:'USADI OTI '},
    {date:'6-17 MAY 2002', topic:'Training of trainers in theatre for development approach ', Sponsor:'SAVE THE CHILDREN UK'},
    {date:'1 AUG 2002', topic:'Participator action research with child in violence', Sponsor:'SAVE THE CHILDREN UK'},
    {date:'18 DEC 2002', topic:'Electoral assistant project', Sponsor:'CRESNET/UNEAD/UNDP'},
    {date:'27 JAN-6FEB 2003', topic:'Children participation in action research with children in violence', Sponsor:'SAVE THE CHILDREN UK'},
    {date:'18-21 MAR 03', topic:'Workshop on conduction research with children at risk', Sponsor:'SAVE THE CHILDREN UK'},
    {date:'MAY 2003', topic:'Participating research with young people in conflict', Sponsor:'SAVE THE CHILDREN UK'},
    {date:'30 JUN 2004', topic:'3 day workshop on legislative advocacy of the national and youth council of Nigeria  ', Sponsor:'Ministry  of sport youth '},
    {date:'AUG 2004', topic:'Television / sponsorship of peace drama series', Sponsor:'Kaduna state gov'},
    {date:'9 AUG 2004', topic:'Introduction to child right programme', Sponsor:'Save the children UK '},
    {date:'8-9 DEC 2004', topic:'Hiv/AIDS media programme sponsorship ', Sponsor:'SACA'},
    {date:'21-23 JUN 2005', topic:'Napep zonal workshop on who is poor? defining poverty north west zone ', Sponsor:'PRECEDENCY, UNICEF, KASTINA STATE GOVOVERNMENT'},
    {date:'2 FEB 2006', topic:'Conflict management workshop for local gov administers in Kaduna state ', Sponsor:'KD SLGC'},
    {date:'13 JUL 2006', topic:'lunching of state of the world children report 2006 ', Sponsor:'UNICEF'},
    {date:'5 JULY 2006', topic:'Meeting of child focus NGO', Sponsor:'MWA/UNICEF'},
    {date:'16 MAR 2007', topic:'A 2days management mechanisim workshop towards peace substance and conflict free election 2007', Sponsor:'Kaduna State government'},
    {date:'14 JUN2007', topic:"Stakeholders meeting on the development aduption of relevant IEC materials on child protection issues for communication in CFO state", Sponsor:'MLUASD'},
    {date:'26 JUN 2007', topic:'A 3 day skill training workshop on child protection and participation', Sponsor:'UNICEF'},
    {date:'2008', topic:'Evaluation of Micro project programme schedule mpp9', Sponsor:'EUROPEAN AID'},
    {date:'21-22 JUL 2008', topic:'Media workshop organized for NGOs to deliver grass roots civic and peace election', Sponsor:'UNDP'},
    {date:'2009', topic:'Two days training for women religious on early warning signs in Kaduna', Sponsor:''},
    {date:'5 DEC 2009', topic:'Training of community tv volunteers', Sponsor:'GLOBAL FOUND'},
    {date:'Dec 2009', topic:'A 2 day training for women religious organisation for early warning signs Kaduna', Sponsor:'USAD'},
    {date:'2010', topic:'Referrer coordinators meeting', Sponsor:'ICAP'},
    {date:'1 JAN 2011', topic:'Global fund TB project agreement ', Sponsor:'GLOBAL FUNDS'},
    {date:'13-14 JAN 2011', topic:'2 days workshop for Kaduna civil partners on budget process ', Sponsor:'CAVI/DEFT'},
    {date:'2011 ', topic:'Youth restiveness and the electoral process in Nigeria', Sponsor:'CRD KANO/INEC'},
    {date:'August 2011', topic:'A two days capacity development for workshop for ward peace / reconciliation in the 23vlga of Kaduna state', Sponsor:''},
    {date:'4-8 NOV 2013', topic:'Forth interaction al conference of forum of cities interasion', Sponsor:'UMASS'},
    {date:'7 AUG 2014', topic:'A lesson learning workshop for the DFID state level programmers', Sponsor:'IMED/DFID'},
    {date:'2-4 SEPT 2014', topic:'Policy review and analysis training', Sponsor:'KAD STA AIDS CONTOL Agency'},
    {date:'10-11 DEC 2014', topic:'Training of community peace building partnership', Sponsor:'AID FOUNDATION /NSRP DFID'},
    {date:'24 JUN 2015', topic:'Women as cardinal tools in the prevention of possible genocide in Nigeria  ', Sponsor:'ALFACARE'},
    {date:'12 AUG 2O15', topic:'Community dialog forum toward establishment of early warning mechanism structure', Sponsor:'NSRP/DFIT'},
    {date:'25 AUG 2015', topic:'A 2  days training on peace building and establishment of early warning mechanism', Sponsor:'NSRP/DFIT'},
    {date:'MAR 2016', topic:'Mobilizing CDA’s as agent of change in the fight against corruption', Sponsor:'ALFACARE'},
    {date:'25 MAR 2016', topic:'Sanitization workshop on human rigt violation complain mechanism (hrvcm) for kano state', Sponsor:'KCFF'},
    {date:'25 AUG 2016', topic:'Anti corruption seminar for community association development (CDA’S) KADUNA state', Sponsor:'Alfacare'},
    {date:'9-20 SEPT 2016', topic:'2 days training on conflict  management on handling styles confidence building , and transformation for entro-religious and political groups', Sponsor:'DAG-NSRP'},
    {date:'31 JAN 2017', topic:'Collective action for adolescent girls', Sponsor:'CAAGI'},
    {date:'17-19 OCT 016', topic:'RELATIONSHIP WITH INSTITUTIONAL ACTORS', Sponsor:'JDBC/observatoire pharos supported european commissions'},
    {date:'22 NOV 2017', topic:'Repositioning women smec for economic development', Sponsor:'KAD GOV'},
    {date:'28-29 NOV 2017', topic:'Early warning  and early response for (CPO’S)', Sponsor:'IMC/USAID'},
    {date:'8-9 APR 2018', topic:'Media talk show on HIV AIDS among muslims communities in Nigeria', Sponsor:'ALFACARE'},
    {date:'JAN 31-FEB 1 2019', topic:'Monitors NEVER training NEVER staffs and lead monitors', Sponsor:'UK AID/ US AID'},
    {date:'AUG 2021', topic:'TRANSFORMING ALMAJIRI SYSTEM OF EDUCATIONIN NORTHERN NIGERIA', Sponsor:'Mc AUTHOR FOUNDATION'},
]